server:
  port:  8880
spring:
  application:
    name: service-application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bozhi?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  redis:
    port: 6379
    host: 127.0.0.1
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: status  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: countSql
